<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mag</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Magpie</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.magpie</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.magpie</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.magpie</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@@).*$\n?</string>
			<key>name</key>
			<string>comment.line.magpie</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.magpie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?\b[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.magpie</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.magpie</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.magpie</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|as|async|break|case|catch|defclass|def|do|else|end|fn|for|if|import|in|is|let|match|or|return|then|throw|var|val|while|with)\b</string>
			<key>name</key>
			<string>keyword.language.magpie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|true|nothing|it)\b</string>
			<key>name</key>
			<string>constant.language.magpie</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\(\)\[\]\{\}\;\,\.]</string>
			<key>name</key>
			<string>punctuation.magpie</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.magpie</string>
	<key>uuid</key>
	<string>4B269243-36A6-4AF9-8CD8-72B7560D1344</string>
</dict>
</plist>
